services:
  db:
    image: postgres:16-alpine
    environment: 
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: servicedb
    ports:
      - "5432:5432"
    volumes:
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      